### PR TITLE
Include option for autoplay direction

### PR DESCRIPTION
**Pull request by baladkb**

### CODE REVIEW

**Comment by equinox7** [comment]
Please, use spaces instead of tabs and I will merge your pull request.

**Comment by baladkb** [comment]
@equinox7 actually I fixed indentation please check https://github.com/baladkb/lbSlider/commit/36624a693cd62e5e5ed9ea4e0dc483e61c4a10ed

**Comment by equinox7** [comment]
You have used tabs. Please, replace them with spaces.
And default autoPlayDirection should be 'right-to-left'.

**Comment by baladkb** [comment]
@equinox7 please check now.

**Comment by equinox7** [comment]
You did not change default option to 'right-to-left', it is still 'left-to-right'. But I can do it by myself.

**Comment by baladkb** [comment]
@equinox7 thanks.

**Comment by cletter7** [comment]
@baladkb Thanks

**Pull request merged**
